// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riumhqlxdmsxwsjstqgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdW1ocWx4ZG1zeHdzanN0cWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjQyNzIsImV4cCI6MjA2MTY0MDI3Mn0.i03WS8CGtEOFJtd88YyeVDuP9mq97At6LkR-Vd2KEcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);